application: simplestockstat
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /apis
  static_dir: apis

- url: /flot
  static_dir: flot
  
- url: /js
  static_dir: js
  

- url: /.*
  script: simplestockstat.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest